# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_machine.ui'
#
# Created: Sun May 24 09:33:41 2009
#      by: PyQt4 UI code generator 4.5-snapshot-20090507
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_NewMachine(object):
    def setupUi(self, NewMachine):
        NewMachine.setObjectName("NewMachine")
        NewMachine.resize(280, 325)
        self.verticalLayout = QtGui.QVBoxLayout(NewMachine)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DataInizio = QtGui.QCalendarWidget(NewMachine)
        self.DataInizio.setObjectName("DataInizio")
        self.verticalLayout.addWidget(self.DataInizio)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(NewMachine)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.Cliente = QtGui.QLineEdit(NewMachine)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Cliente.setPalette(palette)
        self.Cliente.setObjectName("Cliente")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Cliente)
        self.label_2 = QtGui.QLabel(NewMachine)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.Macchina = QtGui.QLineEdit(NewMachine)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.Macchina.setPalette(palette)
        self.Macchina.setObjectName("Macchina")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Macchina)
        self.label_3 = QtGui.QLabel(NewMachine)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.DeltaMesi = QtGui.QSpinBox(NewMachine)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.DeltaMesi.setPalette(palette)
        self.DeltaMesi.setObjectName("DeltaMesi")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.DeltaMesi)
        self.verticalLayout.addLayout(self.formLayout)
        self.isAnticipato = QtGui.QCheckBox(NewMachine)
        self.isAnticipato.setObjectName("isAnticipato")
        self.verticalLayout.addWidget(self.isAnticipato)
        self.buttonBox = QtGui.QDialogButtonBox(NewMachine)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.Cliente)
        self.label_2.setBuddy(self.Macchina)
        self.label_3.setBuddy(self.DeltaMesi)

        self.retranslateUi(NewMachine)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), NewMachine.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), NewMachine.reject)
        QtCore.QMetaObject.connectSlotsByName(NewMachine)

    def retranslateUi(self, NewMachine):
        NewMachine.setWindowTitle(QtGui.QApplication.translate("NewMachine", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewMachine", "Cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewMachine", "Macchina", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewMachine", "Durata contrato", None, QtGui.QApplication.UnicodeUTF8))
        self.DeltaMesi.setSuffix(QtGui.QApplication.translate("NewMachine", " mesi", None, QtGui.QApplication.UnicodeUTF8))
        self.DeltaMesi.setPrefix(QtGui.QApplication.translate("NewMachine", "ogni ", None, QtGui.QApplication.UnicodeUTF8))
        self.isAnticipato.setText(QtGui.QApplication.translate("NewMachine", "Pagamento anticipato", None, QtGui.QApplication.UnicodeUTF8))

